# Generated by Django 3.2 on 2021-04-07 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=64, unique=True, verbose_name="name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=128,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, message="titles cannot be empty!"
                            )
                        ],
                    ),
                ),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                (
                    "body",
                    models.TextField(help_text="The main body for this blog post."),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="blog.Tag"
                    ),
                ),
            ],
        ),
    ]
